version: 2

sources:
  - name: Ecommerce
    schema: raw
    description: "This is the raw ecommerce tables from the source system."
    tables:
      - name: r_customers
        description: "This table contains raw customer data."
        identifier: "customers"
      - name: r_orders
        description: "This table contains raw order data."
        identifier: "orders"
      - name: r_products
        description: "This table contains raw product data."
        identifier: "products"
      - name: r_order_items
        description: "This table contains raw order item data."
        identifier: "order_items"
      - name: r_payments
        description: "This table contains raw payment data."
        identifier: "payments"
      - name: r_sellers
        description: "This table contains raw seller data."
        identifier: "sellers"
      - name: r_reviews
        description: "This table contains raw review data."
        identifier: "reviews"
      - name: r_geolocation
        description: "This table contains raw geolocation data."
        identifier: "geolocation"
      - name: r_product_translation
        description: "This table contains raw product translation data."
        identifier: "product_translation"