name: 'Ecommerce'        # ← must be present
version: '1.0.0'
profile: 'Ecommerce'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  Ecommerce:
    +materialized: view

    staging:
      +materialized: table
      +schema: staging

    intermediate:
      +materialized: table
      +schema: intermediate

    mart:
      +materialized: table
      +schema: mart